{***************************************************************************}
{                                                                           }
{           DUnitX                                                          }
{                                                                           }
{           Copyright (C) 2015 Vincent Parrett & Contributors               }
{                                                                           }
{           vincent@finalbuilder.com                                        }
{           http://www.finalbuilder.com                                     }
{                                                                           }
{                                                                           }
{***************************************************************************}
{                                                                           }
{  Licensed under the Apache License, Version 2.0 (the "License");          }
{  you may not use this file except in compliance with the License.         }
{  You may obtain a copy of the License at                                  }
{                                                                           }
{      http://www.apache.org/licenses/LICENSE-2.0                           }
{                                                                           }
{  Unless required by applicable law or agreed to in writing, software      }
{  distributed under the License is distributed on an "AS IS" BASIS,        }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. }
{  See the License for the specific language governing permissions and      }
{  limitations under the License.                                           }
{                                                                           }
{***************************************************************************}


// Uncomment to use JCL for stacktrace support.
{.$DEFINE USE_JCL}

// Uncomment to use MadExcept 3 for stacktrace support.
{.$DEFINE USE_MADEXCEPT3}

// Uncomment to use MadExcept 4 for stacktrace support.
{.$DEFINE USE_MADEXCEPT4}

// Uncomment to use EurekaLog 7 for stacktrace support.
{.$DEFINE USE_EUREKALOG7}


